version: "3.3"

services:

  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=LR59caK4V9JA16Xga6jtQYl3
      - POSTGRES_USER=server
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - thequestboard

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # image: node:18-alpine
    restart: always
    command: bash -c "npx prisma db push && npx prisma migrate deploy --schema=prisma/schema.prisma && npx prisma generate && npm start"
    working_dir: /backend
    volumes:
      - /backend
    # environment:
    #   - DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_USER}?schema=public"
    ports:
      - 3001:3000
      - 5555:5555
      - 5556:5556
      # - ${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}
    networks:
      - thequestboard
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # image: node:18-alpine
    restart: always
    command: npm run dev
    working_dir: /frontend
    volumes:
      - /frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
      # - ${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}
    networks:
      - thequestboard

volumes:
  db-data:
    driver: local

networks:
  thequestboard:
    driver: bridge